### ISSUE TITLE
Old threads (and related files) do not get deleted(PHP 7.2)

### ISSUE THREAD

**Issue by tunayuyar** [vichan-devel/vichan#345]
Hey @ctrlcctrlv 

I think this is another problem with php7.2 when thread expires thread page and src thumb files do not get deleted. Basically they stay in the directory.

I tried using delete-stray-image.php but that also doesnt work under PHP7.2

I know you dont want to waste time on this anymore just wanted to report.

**Comment by ctrlcctrlv** [comment]
What do you mean by "doesn't work"&mdash;is there an error or is it just a silent failure?

**Comment by tunayuyar** [comment]
This is the error I get when I do "php delete-stray-image.php" from ssh session

/b/... PHP Fatal error:  Uncaught Error: Call to a member function fetch() on boolean in vichan/tools/delete-stray-images.php:25
Stack trace:
#0 {main}
  thrown in vichan/tools/delete-stray-images.php on line 25

Fatal error: Uncaught Error: Call to a member function fetch() on boolean in vichan/tools/delete-stray-images.php:25
Stack trace:
#0 {main}
  thrown in vichan/tools/delete-stray-images.php on line 25
Error: Caught fatal error: Uncaught Error: Call to a member function fetch() on boolean in vichan/tools/delete-stray-images.php:25
Stack trace:
#0 {main}
  thrown in <strong>vichan/tools/delete-stray-images.php</strong> on line 25
#0  error() called at [vichan/inc/functions.php:362]
#1  fatal_error_handler()

**Comment by ctrlcctrlv** [comment]
Does this same error result if you make an OP on a board that is full of threads?

**Comment by tunayuyar** [comment]
What do you mean by make an OP on board? There is no problem opening new threads or posting(if thats what you mean)

**Comment by ctrlcctrlv** [comment]
I mean, is there an error if you make a new thread on a board which is already full

**Comment by tunayuyar** [comment]
Nope no error.

**Comment by ctrlcctrlv** [comment]
OK, I read a little bit and it's because function `query` can return a boolean, so a problem further up the stack is being masked. The code in `delete-stray-images.php` is untouched since _2013_! (There's a reason I recommend people stop using vichan if possible.) I want you to add some code to turn all PDO query failures into errors. This might temporarily make things buggier for you but it will prevent silent failures like this which are masking bugs.

To this function:
https://github.com/vichan-devel/vichan/blob/e15e966cdbda7b658af27b1a498606a82e8f8c5e/inc/database.php#L50

Add 
```php
$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
```


After https://github.com/vichan-devel/vichan/blob/e15e966cdbda7b658af27b1a498606a82e8f8c5e/inc/database.php#L76 (line 76)

Then report back the error that should happen now when you post (and when you run script)

**Comment by tunayuyar** [comment]
This is from delete stray images, let me check php&server log for other errors, should I leave new PDO addition or revert back?


/b/... PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'file' in 'field list' in vichan/inc/database.php:148
Stack trace:
#0 vichan/inc/database.php(148): PDO->query('SELECT `file`, ...')
#1 vichan/tools/delete-stray-images.php(21): query('SELECT `file`, ...')
#2 {main}
  thrown in vichan/inc/database.php on line 148

Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'file' in 'field list' in vichan/inc/database.php:148
Stack trace:
#0 vichan/inc/database.php(148): PDO->query('SELECT `file`, ...')
#1 vichan/tools/delete-stray-images.php(21): query('SELECT `file`, ...')
#2 {main}
  thrown in vichan/inc/database.php on line 148
Error: Caught fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'file' in 'field list' in vichan/inc/database.php:148
Stack trace:
#0 vichan/inc/database.php(148): PDO->query('SELECT `file`, ...')
#1 vichan/tools/delete-stray-images.php(21): query('SELECT `file`, ...')
#2 {main}
  thrown in <strong>vichan/inc/database.php</strong> on line 148
#0  error() called at [vichan/inc/functions.php:362]
#1  fatal_error_handler()

**Comment by ctrlcctrlv** [comment]
So you say this works on PHP5? You've tested that?

**Comment by ctrlcctrlv** [comment]
Because it says your database is missing a column, which would seem true to me on PHP5.

As for the PDO code I just gave you...it's really up to you. It will make sure queries no longer silently fail, but users will get more errors. What's important to you, that things are working right? Or do you prefer living in ignorance? :laughing:

**Comment by tunayuyar** [comment]
I remember it was working before. Also as I said my aim was that old files (images thumbs and html files) should be deleted when they are over their page limit. Right now Im deleting old files by hand, but it is hit and miss this way. 

Ok I'm keeping it.

**Comment by ctrlcctrlv** [comment]
I think what happened here, at least as regards `delete-stray-images.php`, is not the fault of PHP7 @tunayuyar.

https://github.com/vichan-devel/vichan/blob/e15e966cdbda7b658af27b1a498606a82e8f8c5e/templates/posts.sql#L13

This changed six years ago in commit https://github.com/vichan-devel/vichan/commit/c483e1258cb5d168812a6e509e982a172f6c36c6.

So...there is no longer `file` field, it's now called `files`. Remember, I made multi image posting? A long time ago to be sure, I was much thinner for one thing :wink:

So, now that I've figured that out, I'd like to see the error in `clean($pid)` function which is called from `post.php` when new thread is made but board has maximum number of threads.

**Comment by ctrlcctrlv** [comment]
Also @tunayuyar I have some vichan news. Maybe you're interested. https://twitter.com/HW_BEAT_THAT/status/1175715403714056194

Please spread it around if you know any other people still using vichan.

**Comment by tunayuyar** [comment]
@ctrlcctrlv I can delete boards in php7.2, there was always a problem with catalog even in php5 preventing to delete and also overboard was preventing to delete with incorrect settings. 

How can I get the output from post.php you mention?

I don't understand any of this coding/programming stuff really, I'm just reporting maybe it helps someone.

**Comment by ctrlcctrlv** [comment]
Well, just make a new OP post it should fail if you added that PDO code.

If it _doesn't_ fail then I have no idea why old images aren't being deleted for you. Before you make a new OP, take note of which is the last thread on the board so you know what to check if deleted.

By the way, if you email me, you can pay for support, and I will even log in to your server and fix whatever is wrong. $40/hr, paid only in BTC.

**Comment by ctrlcctrlv** [comment]
(If you're not interested in paying for support, I'll only fix bugs if you can show errors and prove where in the code is the problem.)

**Comment by tunayuyar** [comment]
Nope no error whatsoever. I tried when you said it first and can post new threads. 

I wish I can pay, I appreciate your efforts & support on this for years. 

I'm just doing this for hobby to better understand how things work.

**Comment by ctrlcctrlv** [comment]
It's okay, I understand. I'm sorry I can't give more support for free. I'm married now, not just single teenager living in mom's house.

Well, I'd leave the PDO code I gave you in, it will help you figure out if other things are silently failing.

We clearly need a new `delete-stray-images.php` script, but I'm not interested in writing one. I'll open an issue for it though, just so people are aware.

**Comment by tunayuyar** [comment]
Thank you @ctrlcctrlv , I will keep reporting for php 7.2 issues.

**Comment by tunayuyar** [comment]
Also I'm gonna try some mp4s and webms, there were some failing silently.
