### ISSUE TITLE
Call to undefined function _setlocale()

### ISSUE THREAD

**Issue by anoduck** [vichan-devel/vichan#472]
Upon a fresh install, receiving this error when attempting to access the `install.php` script.

```bash
[31-Mar-2022 23:37:17] NOTICE: fpm is running, pid 69
[31-Mar-2022 23:37:17] NOTICE: ready to handle connections
2022/03/31 23:37:28 [error] 75#75: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function _setlocale() in /path/to/vichan/inc/functions.php:31
Stack trace:
#0 /path/to/vichan/inc/functions.php(142): init_locale()
#1 /path/to/vichan/inc/functions.php(20): loadConfig()
#2 /path/to/vichan/vendor/composer/autoload_real.php(55): require('/path/to/vichan...')
#3 /path/to/vichan/vendor/composer/autoload_real.php(38): composerRequirec045553659bfd265410882ed72c4e00e()
#4 /path/to/vichan/vendor/autoload.php(7): ComposerAutoloaderInitc045553659bfd265410882ed72c4e00e::getLoader()
#5 /path/to/vichan/inc/bootstrap.php(3): require_once('/path/to/vichan...')
#6 /path/to/vichan/install.php(5): require('/path/to/vichan...')
#7 {main}
  thrown in /path/to/vichan/inc/functions.php on line 31PHP message: PHP Notice:  Undefined index: syslog in /path/to/vichan/inc/display.php on line 77PHP message: PHP Notice:  Undefined index: debug in /path/to/vichan/inc/display.php on line 89PHP message: PHP Notice:  Undefined index: debug in /path/to/vichan/inc/display.php on line 93PHP message: PHP Notice:  Undefined index: password in /path/to/vichan/inc/display.php on line 107PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function _() in /path/to/vichan/inc/display.php:121
Stack trace:
#0 /path/to/vichan/inc/functions.php(348): error()
#1 [internal function]: fatal_error_handler()
#2 {main}
  thrown in /path/to/vichan/inc/display.php on line 121" while reading response header from upstream, client: 192.168.x.xx, server: _, request: "GET /install.php HTTP/1.1", upstream: "fastcgi://unix:/path/to/php-fpm.sock:", host: "192.168.x.xx"
```

I have a feeling that I have come across this error before, and should be able to resolve this issue with proper setup of php.ini. So, I will leave it open for now. But, it is very familiar.

**Comment by ctrlcctrlv** [comment]
gettext

**Comment by anoduck** [comment]
Sorry...Again...

**Comment by arecio69** [comment]
> gettext

nigga what the fuck does this even mean

**Comment by anoduck** [comment]
Github is not the place for that language. We are adults here, working professionals. That language is completely inappropriate. Remove your comment, and try again.
